# mysql exporter로부터 메트릭 수집하는 ServiceMonitor
# mysql-exporter for helm : https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-mysql-exporter/values.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-db-exporter
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: db-exporter
      app.kubernetes.io/name: prometheus-mysql-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    # ServiceMonitor의 endpoint에서의 port와 targetPort : https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.Endpoint
    - targetPort: 9104
      # port: 9104  # spec.endpoints[0].port in body must be of type string: "integer"
      path: /metrics
      interval: 15s