# Stocks 서비스의 /metrics endpoint로부터 메트릭 수집하는 ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-stocks
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: stocks
  namespaceSelector:
    matchNames: ["default"]
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
