# redis exporter로부터 메트릭 수집하는 ServiceMonitor
# redis-exporter for helm : https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-redis-exporter/values.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-redis-exporter
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: redis-exporter
      app.kubernetes.io/name: prometheus-redis-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    # ServiceMonitor의 endpoint에서의 port와 targetPort : https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.Endpoint
    - targetPort: 9121
      # port: 9121  # spec.endpoints[0].port in body must be of type string: "integer"
      path: /metrics
      interval: 15s



# ServiceMonitor의 label.release는 prometheus CR에 정의된 ServiceMonitorSelector와 같은 것을 사용해야함!
# 그 라벨이 붙은 ServiceMonitor만 수집함
# https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.Prometheus