# mysql exporter로부터 메트릭 수집하는 ServiceMonitor
# mysql-exporter for helm : https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-mysql-exporter/values.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-db-exporter
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: db-exporter
      app.kubernetes.io/name: prometheus-mysql-exporter
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
    - port: 9104
      path: /metrics
      interval: 15s