apiVersion: batch/v1
kind: CronJob
metadata:
  name: rss-scraper
spec:
  schedule: "*/10 * * * *"  # Scraping Interval
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scraper
            image: omoknooni/kubestock-news-scraper:0b6f0c5
            envFrom:
            - secretRef:
                name: news-secret
          restartPolicy: OnFailure