# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rss-news-service
  labels:
    app: rss-news-service
spec:
  type: ClusterIP
  selector:
    app: rss-news-service
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000