apiVersion: batch/v1
kind: CronJob
metadata:
  name: ticker-scraper
spec:
  schedule: "0 4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ticker-scraper
            image: omoknooni/kubestock-stocks-scraper:84aab1d
            args: ["ticker"]
            envFrom:
            - secretRef:
                name: stocks-secret
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: thirteenf-scraper
spec:
  schedule: "0 5 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: report-scraper
            image: omoknooni/kubestock-stocks-scraper:84aab1d
            args: ["thirteenf"]
            envFrom:
            - secretRef:
                name: stocks-secret
          restartPolicy: OnFailure