apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-deployment
  labels:
    app: stocks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stocks
  template:
    metadata:
      labels:
        app: stocks
    spec:
      containers:
      - name: stocks
        image: omoknooni/kubestock-stocks:bccd45f
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: stocks-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: "/data"
              name: redis-storage
      volumes:
        - name: redis-storage
          emptyDir: {}
