apiVersion: apps/v1
kind: Deployment
metadata:
  name: stocks-deployment
  labels:
    app: stocks
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stocks
  template:
    metadata:
      labels:
        app: stocks
    spec:
      containers:
      - name: stocks
        image: omoknooni/kubestock-stocks:latest
        ports:
        - containerPort: 8000
        env:
        - name: STOCK_API_KEY
          valueFrom:
            secretKeyRef:
              name: stocks-secret
              key: STOCK_API_KEY