apiVersion: v1
kind: Service
metadata:
  name: stock-service
  label:
    app: stock-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: stock