apiVersion: v1
kind: Service
metadata:
  name: stocks-service
  labels:
    app: stocks
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: stocks