apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: news-app
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/omoknooni/KubeStock.git
    targetRevision: main
    path: deploy/kubernetes/news
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
