# App-of-apps 패턴을 위한 root app -> 나머지 서비스들을 하위로 관리
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/omoknooni/KubeStock.git
    targetRevision: main
    path: deploy/kubernetes/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
