apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui-service
                port:
                  number: 80
          # - path: /stocks
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: stock-service
          #       port:
          #         number: 80
          # - path: /backtest
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: backtest-service
          #       port:
          #         number: 80