{
 "title": "KubeStock dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Node Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"Ready\", status=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall cluster CPU Consumption (cpu_core unit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[5m])) / sum(machine_cpu_cores) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 Cluster Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5, sum by(pod) (container_memory_usage_bytes{namespace!~\"kube-system\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 CPU-consuming pods",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by(pod) (rate(container_cpu_usage_seconds_total{namespace!~\"kube-system\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage per Pod (cpu-core unit)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 9 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=\"default\"}[5m]))",
     "legendFormat": "{{cronjob}}"
    }
   ]
  },
  {
   "title": "Memory-usage Trand per Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_memory_usage_bytes{namespace!~\"kube-system\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Available Pods per Deployment",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{namespace=\"default\", deployment!~\"db|redis\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}