apiVersion: apps/v1
kind: Deployment
metadata:
  name: backtest-deployment
  labels:
    app: backtest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backtest
  template:
    metadata:
      labels:
        app: backtest
    spec:
      containers:
      - name: backtest
        image: omoknooni/kubestock-backtest:1b4ef96
        ports:
        - containerPort: 8001