apiVersion: v1
kind: Service
metadata:
  name: backtest-service
  labels:
    app: backtest
spec:
  type: ClusterIP
  selector:
    app: backtest
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8001